const EMAIL_TEMPLATE = {
  WORKFLOW_ASSIGNMENT: "WORKFLOW_ASSIGNMENT",
  WORKFLOW_PROVISIONAL_COMMUNICATION: "WORKFLOW_PROVISIONAL_COMMUNICATION",
  WORKFLOW_RATING_LETTER: "WORKFLOW_RATING_LETTER",
  WORKFLOW_PRESS_RELEASE: "WORKFLOW_PRESS_RELEASE",
  DUE_DILLIGENCE: "DUE_DILLIGENCE",
  COMPLETE_RATING_MODEL: "COMPLETE_RATING_MODEL",
  INC_CASE_ENCOUNTERED: "INC_CASE_ENCOUNTERED",
  RATING_HEAD_WORKFLOW_ALERT: "RATING_HEAD_WORKFLOW_ALERT",
  COMPLIANCE: "COMPLIANCE",
  RATING_MODEL: "RATING_MODEL",
  SHARE_PRICE: "SHARE_PRICE",
  DUE_DILIGENCE_MOM: "DUE_DILIGENCE_MOM",
  WORKFLOW_PROVISIONAL_COMMUNICATION_TO_CLIENT: "WORKFLOW_PROVISIONAL_COMMUNICATION_TO_CLIENT",
  WORKFLOW_RATING_LETTER_TO_CLIENT: "WORKFLOW_RATING_LETTER_TO_CLIENT",
  WORKFLOW_PRESS_RELEASE_TO_CLIENT: "WORKFLOW_PRESS_RELEASE_TO_CLIENT"
};
const PRESS_RELEASE_ALERT_DAY = 3;
module.exports = {
  EMAIL_TEMPLATE,
  PRESS_RELEASE_ALERT_DAY,
};
